# Generated by Django 4.0.4 on 2022-05-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pred', models.BooleanField(default=True)),
                ('score', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_review', to='res.res')),
            ],
        ),
    ]
