# Generated by Django 4.0.4 on 2022-06-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_res_reserve_review_unique_author_res_combination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Res_reserve',
            new_name='reserve',
        ),
    ]
