# Generated by Django 4.0.4 on 2022-06-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_rename_res_reserve_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
