# Generated by Django 4.0.4 on 2022-06-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0004_alter_reserve_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
