# Generated by Django 4.0.4 on 2022-05-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='PhoneNumEncrypt',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(max_length=20, unique=True, verbose_name='이메일'),
        ),
    ]
