# Generated by Django 4.0.4 on 2022-05-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_appuser_phonenumencrypt_alter_appuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
